version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: vozpapeladm
      POSTGRES_PASSWORD: VozPapelAdm
      POSTGRES_DB: bdvozdepapel
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
